### ISSUE TITLE
regexp empty check fails for alias/offer/escrow filter calls

### ISSUE THREAD

**Issue by sidhujag** [syscoin/syscoin-client-api-typescript-angular2#3]
https://github.com/syscoin/syscoin-client-api-typescript-angular2/blob/e92880d74f45c5eca26caa1f035ccaa8f3e3b6a3/api/AliasesApi.ts#L120

for example for alias should be "regexp?" and not "regexp", the !regexp call fails below because I pass in "" and then I can't search for all aliases... same thing with escrows.

Offer's has this if ((regexp === null || regexp === undefined))  check which can be removed because its checking for undefined right under it

**Comment by dwasyluk** [comment]
This is generated code, we don't touch it. We just modify the spec to match otherwise we can't reliably use swagger to regen SDKs. This issue should be on https://github.com/syscoin/syscoin-api/issues so I'm moving it there.
